-- Create the EXAM database
CREATE DATABASE EXAM;

-- Use the EXAM database
USE EXAM;

-- Create USERS table
CREATE TABLE USERS (
    id INT PRIMARY KEY,
    NAME VARCHAR(50),
    DOB DATE,
    SCORE FLOAT,
    IS_ACTIVE BOOLEAN
);

-- Insert user records
INSERT INTO USERS VALUES (1, 'HEERA', '2000-09-30', 75.0, 1);
INSERT INTO USERS VALUES (2, 'TEEYA', '2000-09-30', 85.0, 1);
INSERT INTO USERS VALUES (3, 'EYA', '2002-09-03', 45.0, 0);
INSERT INTO USERS VALUES (4, 'VIVEK', '2000-12-21', 95.0, 0);
INSERT INTO USERS VALUES (5, 'DAVID', '2001-11-21', 70.0, 1);
INSERT INTO USERS VALUES (6, 'DAIN', '2000-11-11', 80.0, 1);
INSERT INTO USERS VALUES (7, 'GEORGE', '2002-12-12', 50.0, 0);

-- Query: View all users
SELECT * FROM USERS;

-- Query: View only active users
SELECT * FROM USERS WHERE IS_ACTIVE = 1;

-- Query: Top 5 scores >= 70
SELECT NAME, SCORE FROM USERS 
WHERE SCORE >= 70 
ORDER BY SCORE DESC 
LIMIT 5;

-- Query: View highest scorer
SELECT NAME, SCORE FROM USERS 
WHERE SCORE >= 70 
ORDER BY SCORE DESC 
LIMIT 1;

-- Query: Get unique DOBs
SELECT DISTINCT DOB FROM USERS;

-- Query: Get unique name and DOB pairs
SELECT DISTINCT NAME, DOB FROM USERS;

