CREATE TABLE SCHOOLDETAILS.EMPLOYEES (ID INT PRIMARY KEY,NAME VARCHAR(50),DEPARTMENT VARCHAR(30));

CREATE INDEX dept_index ON SCHOOLDETAILS.EMPLOYEES(DEPARTMENT); 


SELECT * FROM SCHOOLDETAILS.EMPLOYEES WHERE DEPARTMENT = 'IT'; 



ALTER TABLE SCHOOLDETAILS.EMPLOYEES ADD SALARY INT;

INSERT INTO SCHOOLDETAILS.EMPLOYEES (ID, NAME, DEPARTMENT, SALARY)VALUES (1, 'Ravi', 'IT', 50000),
(2, 'Neha', 'HR', 60000),(3, 'Arjun', 'IT', 55000);



SELECT * FROM SCHOOLDETAILS.EMPLOYEES WHERE DEPARTMENT = 'IT';